# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bloom_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62loom_service.proto\x12\rbloom_service\"\x1e\n\x0cInputMessage\x12\x0e\n\x06prompt\x18\x01 \x01(\t\".\n\rOutputMessage\x12\x0f\n\x07partial\x18\x01 \x01(\t\x12\x0c\n\x04prob\x18\x02 \x01(\x02\x32U\n\x0c\x42loomService\x12\x45\n\x04\x43hat\x12\x1b.bloom_service.InputMessage\x1a\x1c.bloom_service.OutputMessage\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bloom_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUTMESSAGE']._serialized_start=38
  _globals['_INPUTMESSAGE']._serialized_end=68
  _globals['_OUTPUTMESSAGE']._serialized_start=70
  _globals['_OUTPUTMESSAGE']._serialized_end=116
  _globals['_BLOOMSERVICE']._serialized_start=118
  _globals['_BLOOMSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
